# Solving Sudoku Puzzles
## Assignment Preamble
Please ensure you carefully read all of the details and instructions on the assignment page, this section, and the rest of the notebook. If anything is unclear at any time please post on the forum or ask a tutor well in advance of the assignment deadline.

In addition to all of the instructions in the body of the assignment below, you must also follow the following technical instructions for all assignments in this unit. *Failure to do so may result in a grade of zero.*
* [At the bottom of the page](#Submission-Test) is some code which checks you meet the submission requirements. You **must** ensure that this runs correctly before submission.
* Do not modify or delete any of the cells that are marked as test cells, even if they appear to be empty.
* Do not duplicate any cells in the notebook – this can break the marking script. Instead, insert a new cell (e.g. from the menu) and copy across any contents as necessary.

Remember to save and backup your work regularly, and double-check you are submitting the correct version.

This notebook is the primary reference for your submission. You may write code in separate `.py` files but it must be clearly imported into the notebook so that it runs without needing to reference those files, and you must explain clearly what functionality is contained in those files (through comments, markdown cells, etc).

As always, **the work you submit for this assignment must be entirely your own.** Do not copy or work with other students. Do not copy answers that you find online. These assignments are designed to help improve your understanding first and foremost – the process of doing the assignment is part of *learning*. They are also used to assess your ability, and so you must uphold academic integrity. Submitting plagiarised work risks your entire place on your degree.

**You must implement your own work.** You can and are encouraged to use helper libraries like `numpy`, but you must not use 3rd-party libraries or code that solves the assignment for you. *Even if it is properly referenced*, you only get marks for work you have done. If you are unsure, ask on the forum or ask a tutor directly.

**The pass mark for this assignment is 40%.** We expect that students, on average, will be able to produce a submission which gets a mark between 50-70% within the normal workload allocation for the unit, but this will vary depending on individual backgrounds. Please ask for help if you are struggling.

## Getting Started
For this assignment, you will be writing an agent that can solve sudoku puzzles. You should be familiar with sudoku puzzles from the unit material. You are given a 9x9 grid with some fixed values. To solve the puzzle, the objective is to fill the empty cells of the grid such that the numbers 1 to 9 appear exactly once in each row, column, and 3x3 block of the grid. 

Below is a sample puzzle along with its solution. 

<img src="images/sudoku.png" style="width: 50%;"/>

For this assignment you will need to submit:
1. The implementation for an agent which can solve sudoku puzzles – this notebook
 * You can use any algorithm you like, from the unit material or otherwise
 * Your code will be subject to automated testing, from which grades will be assigned based on whether it can solve sudokus of varying difficulty
 * To get a high grade on this assignment, the speed of your code will also be a factor – the quicker the better
 * There are some sample tests included below, make sure your code is compatible with the format of these tests
2. A text file that explains your approach and the decisions you made in your own words – a readme file
 * Submissions that do not include the written section will receive zero marks – **this part is mandatory**
 * You may write your file in plain text (.txt) or [Markdown](https://www.markdownguide.org/basic-syntax/) (.md)
 * To get top marks on this assignment, as well as getting a high grade from your implementation, you must also demonstrate excellent academic presentation in your written section

### Choice of Algorithm
The choice of algorithm to solve sudoku puzzles is up to you. We expect you will use search techniques from the unit, but you could make something up yourself, or do some independent research to find something else. You will need to evaluate and balance the trade-off between how well suited you think the algorithm is and how difficult it is to write, but there is some advice below.

You should also consider what *data structures* you use within your code. Certain algorithms will work much faster with certain data structures, and understanding this is considered part of understanding the algorithm itself. 

I suggest you implement *constraint satisfaction* as it is described in the unit material. A good implementation of a backtracking depth-first search with constraint propagation should be sufficient to get a good grade in the automated tests (roughly 60-70%). There is an example of constraint satisfaction on the eight-queens puzzle, and you could use this as a guide to help you get started.

You could also write a successful agent that uses the other search techniques you have seen in the unit so far: basic search, heuristic search, or local search. You may find these easier to implement, though they may perform less well. 

To get a high grade on this assignment will require a particularly efficient implementation of constraint satisfaction, or something which goes beyond the material we have presented. *This is left unguided and is not factored into the unit workload estimates.*

If you choose to implement more than one algorithm, please feel free to include your code and write about it in part two (readme file), but only the code in this notebook will be used in the automated testing.

## Sample Sudoku Puzzles
To get started, the cell below will load in some sample sudoku puzzles for you so you can see the format. There are sudokus provided of multiple difficulties (easier sudokus typically start with more digits provided). The cell below only loads the easiest, but there is another test cell lower in the notebook which will run your code against all of the provided puzzles.

Each sudoku is a 9x9 NumPy array of integers, where zero represents an empty square. Each difficulty comes with 15 sudokus, so when you load the file, it is stored in a 15x9x9 array.

In [1]:
import numpy as np

# Load sudokus
sudoku = np.load("data/very_easy_puzzle.npy")
print("very_easy_puzzle.npy has been loaded into the variable sudoku")
print(f"sudoku.shape: {sudoku.shape}, sudoku[0].shape: {sudoku[0].shape}, sudoku.dtype: {sudoku.dtype}")

# Load solutions for demonstration
solutions = np.load("data/very_easy_solution.npy")
print()

# Print the first 9x9 sudoku...
print("First sudoku:")
print(sudoku[0], "\n")

# ...and its solution
print("Solution of first sudoku:")
print(solutions[0])

very_easy_puzzle.npy has been loaded into the variable sudoku
sudoku.shape: (15, 9, 9), sudoku[0].shape: (9, 9), sudoku.dtype: int8

First sudoku:
[[1 0 4 3 8 2 9 5 6]
 [2 0 5 4 6 7 1 3 8]
 [3 8 6 9 5 1 4 0 2]
 [4 6 1 5 2 3 8 9 7]
 [7 3 8 1 4 9 6 2 5]
 [9 5 2 8 7 6 3 1 4]
 [5 2 9 6 3 4 7 8 1]
 [6 0 7 2 9 8 5 4 3]
 [8 4 3 0 1 5 2 6 9]] 

Solution of first sudoku:
[[1 7 4 3 8 2 9 5 6]
 [2 9 5 4 6 7 1 3 8]
 [3 8 6 9 5 1 4 7 2]
 [4 6 1 5 2 3 8 9 7]
 [7 3 8 1 4 9 6 2 5]
 [9 5 2 8 7 6 3 1 4]
 [5 2 9 6 3 4 7 8 1]
 [6 1 7 2 9 8 5 4 3]
 [8 4 3 7 1 5 2 6 9]]


## Part One
You should write all of your code for solving sudokus below this cell.

You must include a function called `sudoku_solver(sudoku)` which takes one sudoku puzzle (a 9x9 NumPy array) as input, and returns the solved sudoku as another 9x9 NumPy array. This is the function which will be tested. 

In [2]:
def sudoku_solver(sudoku):
    """
    Solves a Sudoku puzzle and returns its unique solution.

    Input
        sudoku : 9x9 numpy array
            Empty cells are designated by 0.

    Output
        9x9 numpy array of integers
            It contains the solution, if there is one. If there is no solution, all array entries should be -1.
    """
    ### YOUR CODE HERE
    valid_state = True 
    rows_check = []
    columns_check = []
    for x in range(1,10) : 
        rows = np.count_nonzero(sudoku == x, axis = 1)
        columns = np.count_nonzero(sudoku == x, axis = 0)
        for y in rows : 
            rows_check.append(y)
        for z in columns : 
            columns_check.append(z)
    for a in set(rows_check) : 
        if a > 1 : 
            valid_state = False
            for x,y in np.ndenumerate(sudoku) : 
                sudoku[x[0]][x[1]] = -1
    for b in set(columns_check) : 
        if b > 1 : 
            valid_state = False 
            for x,y in np.ndenumerate(sudoku) : 
                sudoku[x[0]][x[1]] = -1
    while np.sum(sudoku) != 405 and valid_state :
        not_in_row_1 = [x for x in range(1,10) if x not in sudoku[0,:]]
        not_in_row_2 = [x for x in range(1,10) if x not in sudoku[1,:]]
        not_in_row_3 = [x for x in range(1,10) if x not in sudoku[2,:]]
        not_in_row_4 = [x for x in range(1,10) if x not in sudoku[3,:]]
        not_in_row_5 = [x for x in range(1,10) if x not in sudoku[4,:]]
        not_in_row_6 = [x for x in range(1,10) if x not in sudoku[5,:]]
        not_in_row_7 = [x for x in range(1,10) if x not in sudoku[6,:]]
        not_in_row_8 = [x for x in range(1,10) if x not in sudoku[7,:]]
        not_in_row_9 = [x for x in range(1,10) if x not in sudoku[8,:]]
        not_in_column_1 = [x for x in range(1,10) if x not in sudoku[:,0]]
        not_in_column_2 = [x for x in range(1,10) if x not in sudoku[:,1]]
        not_in_column_3 = [x for x in range(1,10) if x not in sudoku[:,2]]
        not_in_column_4 = [x for x in range(1,10) if x not in sudoku[:,3]]
        not_in_column_5 = [x for x in range(1,10) if x not in sudoku[:,4]]
        not_in_column_6 = [x for x in range(1,10) if x not in sudoku[:,5]]
        not_in_column_7 = [x for x in range(1,10) if x not in sudoku[:,6]]
        not_in_column_8 = [x for x in range(1,10) if x not in sudoku[:,7]]
        not_in_column_9 = [x for x in range(1,10) if x not in sudoku[:,8]]
        not_in_subblock_1 = [x for x in range(1,10) if x not in sudoku[0:3,0:3]]
        not_in_subblock_2 = [x for x in range(1,10) if x not in sudoku[0:3,3:6]]
        not_in_subblock_3 = [x for x in range(1,10) if x not in sudoku[0:3,6:]]
        not_in_subblock_4 = [x for x in range(1,10) if x not in sudoku[3:6,0:3]]
        not_in_subblock_5 = [x for x in range(1,10) if x not in sudoku[3:6,3:6]]
        not_in_subblock_6 = [x for x in range(1,10) if x not in sudoku[3:6,6:]]
        not_in_subblock_7 = [x for x in range(1,10) if x not in sudoku[6:,0:3]]
        not_in_subblock_8 = [x for x in range(1,10) if x not in sudoku[6:,3:6]]
        not_in_subblock_9 = [x for x in range(1,10) if x not in sudoku[6:,6:]]
        all_indices = []
        for idx, x in np.ndenumerate(sudoku) : 
            all_indices.append(idx)
        subblock_1_indices = [x for x in all_indices if x[0] in [0,1,2] and x[1] in [0,1,2]]
        subblock_2_indices = [x for x in all_indices if x[0] in [0,1,2] and x[1] in [3,4,5]]
        subblock_3_indices = [x for x in all_indices if x[0] in [0,1,2] and x[1] in [6,7,8]]
        subblock_4_indices = [x for x in all_indices if x[0] in [3,4,5] and x[1] in [0,1,2]]
        subblock_5_indices = [x for x in all_indices if x[0] in [3,4,5] and x[1] in [3,4,5]]
        subblock_6_indices = [x for x in all_indices if x[0] in [3,4,5] and x[1] in [6,7,8]]
        subblock_7_indices = [x for x in all_indices if x[0] in [6,7,8] and x[1] in [0,1,2]]
        subblock_8_indices = [x for x in all_indices if x[0] in [6,7,8] and x[1] in [3,4,5]]
        subblock_9_indices = [x for x in all_indices if x[0] in [6,7,8] and x[1] in [6,7,8]]
        empty_fields = []
        for idx, x in np.ndenumerate(sudoku):
            if x == 0 : 
                empty_fields.append(idx)
        not_in_all_columns = [not_in_column_1, not_in_column_2, not_in_column_3, not_in_column_4, not_in_column_5, 
                              not_in_column_6, not_in_column_7, not_in_column_8, not_in_column_9]
        not_in_all_rows = [not_in_row_1, not_in_row_2,not_in_row_3,not_in_row_4,not_in_row_5,
                           not_in_row_6,not_in_row_7,not_in_row_8,not_in_row_9]
        not_in_all_subblocks = [not_in_subblock_1,not_in_subblock_2,not_in_subblock_3,not_in_subblock_4,not_in_subblock_5,not_in_subblock_6,
                                not_in_subblock_7,not_in_subblock_8,not_in_subblock_9]
        possible_solutions_sequence = dict()
        for x in empty_fields : 
            if x in subblock_1_indices : 
                row_num = x[0]
                col_num = x[1]
                tmp = [number for number in range(1,10) if number in not_in_subblock_1 and number in not_in_all_rows[row_num] 
                       and number in not_in_all_columns[col_num]]
                possible_solutions_sequence[x] = tmp 
            elif x in subblock_2_indices : 
                row_num = x[0]
                col_num = x[1]
                tmp = [number for number in range(1,10) if number in not_in_subblock_2 and number in not_in_all_rows[row_num] 
                       and number in not_in_all_columns[col_num]]
                possible_solutions_sequence[x] = tmp
            elif x in subblock_3_indices : 
                row_num = x[0]
                col_num = x[1]
                tmp = [number for number in range(1,10) if number in not_in_subblock_3 and number in not_in_all_rows[row_num] 
                       and number in not_in_all_columns[col_num]]
                possible_solutions_sequence[x] = tmp
            elif x in subblock_4_indices : 
                row_num = x[0]
                col_num = x[1]
                tmp = [number for number in range(1,10) if number in not_in_subblock_4 and number in not_in_all_rows[row_num] 
                       and number in not_in_all_columns[col_num]]
                possible_solutions_sequence[x] = tmp
            elif x in subblock_5_indices : 
                row_num = x[0]
                col_num = x[1]
                tmp = [number for number in range(1,10) if number in not_in_subblock_5 and number in not_in_all_rows[row_num] 
                       and number in not_in_all_columns[col_num]]
                possible_solutions_sequence[x] = tmp
            elif x in subblock_6_indices : 
                row_num = x[0]
                col_num = x[1]
                tmp = [number for number in range(1,10) if number in not_in_subblock_6 and number in not_in_all_rows[row_num] 
                       and number in not_in_all_columns[col_num]]
                possible_solutions_sequence[x] = tmp
            elif x in subblock_7_indices : 
                row_num = x[0]
                col_num = x[1]
                tmp = [number for number in range(1,10) if number in not_in_subblock_7 and number in not_in_all_rows[row_num] 
                       and number in not_in_all_columns[col_num]]
                possible_solutions_sequence[x] = tmp
            elif x in subblock_8_indices : 
                row_num = x[0]
                col_num = x[1]
                tmp = [number for number in range(1,10) if number in not_in_subblock_8 and number in not_in_all_rows[row_num] 
                       and number in not_in_all_columns[col_num]]
                possible_solutions_sequence[x] = tmp
            elif x in subblock_9_indices : 
                row_num = x[0]
                col_num = x[1]
                tmp = [number for number in range(1,10) if number in not_in_subblock_9 and number in not_in_all_rows[row_num] 
                       and number in not_in_all_columns[col_num]]
                possible_solutions_sequence[x] = tmp
        fields_single_solutions = [x for x in [y for y in possible_solutions_sequence.values()] if len(x) == 1]
        if len(fields_single_solutions) > 0 : 
            for x in empty_fields : 
                if len(possible_solutions_sequence[x]) == 1 :
                    sudoku[x[0], x[1]] = possible_solutions_sequence[x][0]
        else : 
            subblock_1_hash = {}
            subblock_2_hash = {}
            subblock_3_hash = {}
            subblock_4_hash = {}
            subblock_5_hash = {}
            subblock_6_hash = {}
            subblock_7_hash = {}
            subblock_8_hash = {}
            subblock_9_hash = {}
            for x in empty_fields : 
                if len(possible_solutions_sequence[x]) > 1 and x in subblock_1_indices : 
                    subblock_1_hash[x] = possible_solutions_sequence[x]
                elif len(possible_solutions_sequence[x]) > 1 and x in subblock_2_indices : 
                    subblock_2_hash[x] = possible_solutions_sequence[x]
                elif len(possible_solutions_sequence[x]) > 1 and x in subblock_3_indices : 
                    subblock_3_hash[x] = possible_solutions_sequence[x]
                elif len(possible_solutions_sequence[x]) > 1 and x in subblock_4_indices : 
                    subblock_4_hash[x] = possible_solutions_sequence[x]
                elif len(possible_solutions_sequence[x]) > 1 and x in subblock_5_indices : 
                    subblock_5_hash[x] = possible_solutions_sequence[x]
                elif len(possible_solutions_sequence[x]) > 1 and x in subblock_6_indices : 
                    subblock_6_hash[x] = possible_solutions_sequence[x]
                elif len(possible_solutions_sequence[x]) > 1 and x in subblock_7_indices : 
                    subblock_7_hash[x] = possible_solutions_sequence[x]
                elif len(possible_solutions_sequence[x]) > 1 and x in subblock_8_indices : 
                    subblock_8_hash[x] = possible_solutions_sequence[x]
                elif len(possible_solutions_sequence[x]) > 1 and x in subblock_9_indices : 
                    subblock_9_hash[x] = possible_solutions_sequence[x]     
            solutions_block_1 = [val for sublist in [x for x in subblock_1_hash.values()] for val in sublist]
            solutions_block_2 = [val for sublist in [x for x in subblock_2_hash.values()] for val in sublist]
            solutions_block_3 = [val for sublist in [x for x in subblock_3_hash.values()] for val in sublist]
            solutions_block_4 = [val for sublist in [x for x in subblock_4_hash.values()] for val in sublist]
            solutions_block_5 = [val for sublist in [x for x in subblock_5_hash.values()] for val in sublist]
            solutions_block_6 = [val for sublist in [x for x in subblock_6_hash.values()] for val in sublist]
            solutions_block_7 = [val for sublist in [x for x in subblock_7_hash.values()] for val in sublist]
            solutions_block_8 = [val for sublist in [x for x in subblock_8_hash.values()] for val in sublist]
            solutions_block_9 = [val for sublist in [x for x in subblock_9_hash.values()] for val in sublist]
            unique_solutions_block_1 = [x for x in solutions_block_1 if solutions_block_1.count(x) == 1]
            unique_solutions_block_2 = [x for x in solutions_block_2 if solutions_block_2.count(x) == 1]
            unique_solutions_block_3 = [x for x in solutions_block_3 if solutions_block_3.count(x) == 1]
            unique_solutions_block_4 = [x for x in solutions_block_4 if solutions_block_4.count(x) == 1]
            unique_solutions_block_5 = [x for x in solutions_block_5 if solutions_block_5.count(x) == 1]
            unique_solutions_block_6 = [x for x in solutions_block_6 if solutions_block_6.count(x) == 1]
            unique_solutions_block_7 = [x for x in solutions_block_7 if solutions_block_7.count(x) == 1]
            unique_solutions_block_8 = [x for x in solutions_block_8 if solutions_block_8.count(x) == 1]
            unique_solutions_block_9 = [x for x in solutions_block_9 if solutions_block_9.count(x) == 1]
            for x, y in enumerate(empty_fields) :
                if y in subblock_1_indices : 
                    for x in subblock_1_hash.items() : 
                        for y in unique_solutions_block_1 : 
                            if y in x[1] : 
                                sudoku[x[0][0], x[0][1]] = y
                elif y in subblock_2_indices : 
                    for x in subblock_2_hash.items() : 
                        for y in unique_solutions_block_2 : 
                            if y in x[1] : 
                                sudoku[x[0][0], x[0][1]] = y
                elif y in subblock_3_indices : 
                    for x in subblock_3_hash.items() : 
                        for y in unique_solutions_block_3 : 
                            if y in x[1] : 
                                sudoku[x[0][0], x[0][1]] = y
                elif y in subblock_4_indices : 
                    for x in subblock_4_hash.items() : 
                        for y in unique_solutions_block_4 : 
                            if y in x[1] : 
                                sudoku[x[0][0], x[0][1]] = y
                elif y in subblock_5_indices : 
                    for x in subblock_5_hash.items() : 
                        for y in unique_solutions_block_5 : 
                            if y in x[1] : 
                                sudoku[x[0][0], x[0][1]] = y
                elif y in subblock_6_indices : 
                    for x in subblock_6_hash.items() : 
                        for y in unique_solutions_block_6 : 
                            if y in x[1] : 
                                sudoku[x[0][0], x[0][1]] = y
                elif y in subblock_7_indices : 
                    for x in subblock_7_hash.items() : 
                        for y in unique_solutions_block_7 : 
                            if y in x[1] : 
                                sudoku[x[0][0], x[0][1]] = y
                elif y in subblock_8_indices : 
                    for x in subblock_8_hash.items() : 
                        for y in unique_solutions_block_8 : 
                            if y in x[1] : 
                                sudoku[x[0][0], x[0][1]] = y
                elif y in subblock_9_indices : 
                    for x in subblock_9_hash.items() : 
                        for y in unique_solutions_block_9 : 
                            if y in x[1] : 
                                sudoku[x[0][0], x[0][1]] = y
            row_1_hash = {}
            row_2_hash = {}
            row_3_hash = {}
            row_4_hash = {}
            row_5_hash = {}
            row_6_hash = {}
            row_7_hash = {}
            row_8_hash = {}
            row_9_hash = {}
            row_1_indices = [x for x in all_indices if x[0] == 0]
            row_2_indices = [x for x in all_indices if x[0] == 1]
            row_3_indices = [x for x in all_indices if x[0] == 2]
            row_4_indices = [x for x in all_indices if x[0] == 3]
            row_5_indices = [x for x in all_indices if x[0] == 4]
            row_6_indices = [x for x in all_indices if x[0] == 5]
            row_7_indices = [x for x in all_indices if x[0] == 6]
            row_8_indices = [x for x in all_indices if x[0] == 7]
            row_9_indices = [x for x in all_indices if x[0] == 8]
            for x in empty_fields : 
                if len(possible_solutions_sequence[x]) > 1 and x in row_1_indices : 
                    row_1_hash[x] = possible_solutions_sequence[x]
                elif len(possible_solutions_sequence[x]) > 1 and x in row_2_indices : 
                    row_2_hash[x] = possible_solutions_sequence[x]
                elif len(possible_solutions_sequence[x]) > 1 and x in row_3_indices : 
                    row_3_hash[x] = possible_solutions_sequence[x]
                elif len(possible_solutions_sequence[x]) > 1 and x in row_4_indices : 
                    row_4_hash[x] = possible_solutions_sequence[x]
                elif len(possible_solutions_sequence[x]) > 1 and x in row_5_indices : 
                    row_5_hash[x] = possible_solutions_sequence[x]
                elif len(possible_solutions_sequence[x]) > 1 and x in row_6_indices : 
                    row_6_hash[x] = possible_solutions_sequence[x]
                elif len(possible_solutions_sequence[x]) > 1 and x in row_7_indices : 
                    row_7_hash[x] = possible_solutions_sequence[x]
                elif len(possible_solutions_sequence[x]) > 1 and x in row_8_indices : 
                    row_8_hash[x] = possible_solutions_sequence[x]
                elif len(possible_solutions_sequence[x]) > 1 and x in row_9_indices : 
                    row_9_hash[x] = possible_solutions_sequence[x] 
            solutions_row_1 = [val for sublist in [x for x in row_1_hash.values()] for val in sublist]
            solutions_row_2 = [val for sublist in [x for x in row_2_hash.values()] for val in sublist]
            solutions_row_3 = [val for sublist in [x for x in row_3_hash.values()] for val in sublist]
            solutions_row_4 = [val for sublist in [x for x in row_4_hash.values()] for val in sublist]
            solutions_row_5 = [val for sublist in [x for x in row_5_hash.values()] for val in sublist]
            solutions_row_6 = [val for sublist in [x for x in row_6_hash.values()] for val in sublist]
            solutions_row_7 = [val for sublist in [x for x in row_7_hash.values()] for val in sublist]
            solutions_row_8 = [val for sublist in [x for x in row_8_hash.values()] for val in sublist]
            solutions_row_9 = [val for sublist in [x for x in row_9_hash.values()] for val in sublist]
            unique_solutions_row_1 = [x for x in solutions_row_1 if solutions_row_1.count(x) == 1]
            unique_solutions_row_2 = [x for x in solutions_row_2 if solutions_row_2.count(x) == 1]
            unique_solutions_row_3 = [x for x in solutions_row_3 if solutions_row_3.count(x) == 1]
            unique_solutions_row_4 = [x for x in solutions_row_4 if solutions_row_4.count(x) == 1]
            unique_solutions_row_5 = [x for x in solutions_row_5 if solutions_row_5.count(x) == 1]
            unique_solutions_row_6 = [x for x in solutions_row_6 if solutions_row_6.count(x) == 1]
            unique_solutions_row_7 = [x for x in solutions_row_7 if solutions_row_7.count(x) == 1]
            unique_solutions_row_8 = [x for x in solutions_row_8 if solutions_row_8.count(x) == 1]
            unique_solutions_row_9 = [x for x in solutions_row_9 if solutions_row_9.count(x) == 1]
            for x, y in enumerate(empty_fields) :
                if y in row_1_indices : 
                    for x in row_1_hash.items() : 
                        for y in unique_solutions_row_1 : 
                            if y in x[1] : 
                                sudoku[x[0][0], x[0][1]] = y
                elif y in row_2_indices : 
                    for x in row_2_hash.items() : 
                        for y in unique_solutions_row_2 : 
                            if y in x[1] : 
                                sudoku[x[0][0], x[0][1]] = y
                elif y in row_3_indices : 
                    for x in row_3_hash.items() : 
                        for y in unique_solutions_row_3 : 
                            if y in x[1] : 
                                sudoku[x[0][0], x[0][1]] = y
                elif y in row_3_indices : 
                    for x in row_3_hash.items() : 
                        for y in unique_solutions_row_3 : 
                            if y in x[1] : 
                                sudoku[x[0][0], x[0][1]] = y
                elif y in row_4_indices : 
                    for x in row_4_hash.items() : 
                        for y in unique_solutions_row_4 : 
                            if y in x[1] : 
                                sudoku[x[0][0], x[0][1]] = y
                elif y in row_5_indices : 
                    for x in row_5_hash.items() : 
                        for y in unique_solutions_row_5 : 
                            if y in x[1] : 
                                sudoku[x[0][0], x[0][1]] = y
                elif y in row_6_indices : 
                    for x in row_6_hash.items() : 
                        for y in unique_solutions_row_6 : 
                            if y in x[1] : 
                                sudoku[x[0][0], x[0][1]] = y
                elif y in row_7_indices : 
                    for x in row_7_hash.items() : 
                        for y in unique_solutions_row_7 : 
                            if y in x[1] : 
                                sudoku[x[0][0], x[0][1]] = y
                elif y in row_8_indices : 
                    for x in row_8_hash.items() : 
                        for y in unique_solutions_row_8 : 
                            if y in x[1] : 
                                sudoku[x[0][0], x[0][1]] = y
                elif y in row_9_indices : 
                    for x in row_9_hash.items() : 
                        for y in unique_solutions_row_9 : 
                            if y in x[1] : 
                                sudoku[x[0][0], x[0][1]] = y
            column_1_hash = {}
            column_2_hash = {}
            column_3_hash = {}
            column_4_hash = {}
            column_5_hash = {}
            column_6_hash = {}
            column_7_hash = {}
            column_8_hash = {}
            column_9_hash = {}
            column_1_indices = [x for x in all_indices if x[1] == 0]
            column_2_indices = [x for x in all_indices if x[1] == 1]
            column_3_indices = [x for x in all_indices if x[1] == 2]
            column_4_indices = [x for x in all_indices if x[1] == 3]
            column_5_indices = [x for x in all_indices if x[1] == 4]
            column_6_indices = [x for x in all_indices if x[1] == 5]
            column_7_indices = [x for x in all_indices if x[1] == 6]
            column_8_indices = [x for x in all_indices if x[1] == 7]
            column_9_indices = [x for x in all_indices if x[1] == 8]
            for x in empty_fields : 
                if len(possible_solutions_sequence[x]) > 1 and x in column_1_indices : 
                    column_1_hash[x] = possible_solutions_sequence[x]
                elif len(possible_solutions_sequence[x]) > 1 and x in column_2_indices : 
                    column_2_hash[x] = possible_solutions_sequence[x]
                elif len(possible_solutions_sequence[x]) > 1 and x in column_3_indices : 
                    column_3_hash[x] = possible_solutions_sequence[x]
                elif len(possible_solutions_sequence[x]) > 1 and x in column_4_indices : 
                    column_4_hash[x] = possible_solutions_sequence[x]
                elif len(possible_solutions_sequence[x]) > 1 and x in column_5_indices : 
                    column_5_hash[x] = possible_solutions_sequence[x]
                elif len(possible_solutions_sequence[x]) > 1 and x in column_6_indices : 
                    column_6_hash[x] = possible_solutions_sequence[x]
                elif len(possible_solutions_sequence[x]) > 1 and x in column_7_indices : 
                    column_7_hash[x] = possible_solutions_sequence[x]
                elif len(possible_solutions_sequence[x]) > 1 and x in column_8_indices : 
                    column_8_hash[x] = possible_solutions_sequence[x]
                elif len(possible_solutions_sequence[x]) > 1 and x in column_9_indices : 
                    column_9_hash[x] = possible_solutions_sequence[x] 
            solutions_column_1 = [val for sublist in [x for x in column_1_hash.values()] for val in sublist]
            solutions_column_2 = [val for sublist in [x for x in column_2_hash.values()] for val in sublist]
            solutions_column_3 = [val for sublist in [x for x in column_3_hash.values()] for val in sublist]
            solutions_column_4 = [val for sublist in [x for x in column_4_hash.values()] for val in sublist]
            solutions_column_5 = [val for sublist in [x for x in column_5_hash.values()] for val in sublist]
            solutions_column_6 = [val for sublist in [x for x in column_6_hash.values()] for val in sublist]
            solutions_column_7 = [val for sublist in [x for x in column_7_hash.values()] for val in sublist]
            solutions_column_8 = [val for sublist in [x for x in column_8_hash.values()] for val in sublist]
            solutions_column_9 = [val for sublist in [x for x in column_9_hash.values()] for val in sublist]
            unique_solutions_column_1 = [x for x in solutions_column_1 if solutions_column_1.count(x) == 1]
            unique_solutions_column_2 = [x for x in solutions_column_2 if solutions_column_2.count(x) == 1]
            unique_solutions_column_3 = [x for x in solutions_column_3 if solutions_column_3.count(x) == 1]
            unique_solutions_column_4 = [x for x in solutions_column_4 if solutions_column_4.count(x) == 1]
            unique_solutions_column_5 = [x for x in solutions_column_5 if solutions_column_5.count(x) == 1]
            unique_solutions_column_6 = [x for x in solutions_column_6 if solutions_column_6.count(x) == 1]
            unique_solutions_column_7 = [x for x in solutions_column_7 if solutions_column_7.count(x) == 1]
            unique_solutions_column_8 = [x for x in solutions_column_8 if solutions_column_8.count(x) == 1]
            unique_solutions_column_9 = [x for x in solutions_column_9 if solutions_column_9.count(x) == 1]
            for x, y in enumerate(empty_fields) :
                if y in column_1_indices : 
                    for x in column_1_hash.items() : 
                        for y in unique_solutions_column_1 : 
                            if y in x[1] : 
                                sudoku[x[0][0], x[0][1]] = y
                elif y in column_2_indices : 
                    for x in column_2_hash.items() : 
                        for y in unique_solutions_column_2 : 
                            if y in x[1] : 
                                sudoku[x[0][0], x[0][1]] = y
                elif y in column_3_indices : 
                    for x in column_3_hash.items() : 
                        for y in unique_solutions_column_3 : 
                            if y in x[1] : 
                                sudoku[x[0][0], x[0][1]] = y
                elif y in column_3_indices : 
                    for x in column_3_hash.items() : 
                        for y in unique_solutions_column_3 : 
                            if y in x[1] : 
                                sudoku[x[0][0], x[0][1]] = y
                elif y in column_4_indices : 
                    for x in column_4_hash.items() : 
                        for y in unique_solutions_column_4 : 
                            if y in x[1] : 
                                sudoku[x[0][0], x[0][1]] = y
                elif y in column_5_indices : 
                    for x in column_5_hash.items() : 
                        for y in unique_solutions_column_5 : 
                            if y in x[1] : 
                                sudoku[x[0][0], x[0][1]] = y
                elif y in column_6_indices : 
                    for x in column_6_hash.items() : 
                        for y in unique_solutions_column_6 : 
                            if y in x[1] : 
                                sudoku[x[0][0], x[0][1]] = y
                elif y in column_7_indices : 
                    for x in column_7_hash.items() : 
                        for y in unique_solutions_column_7 : 
                            if y in x[1] : 
                                sudoku[x[0][0], x[0][1]] = y
                elif y in column_8_indices : 
                    for x in column_8_hash.items() : 
                        for y in unique_solutions_column_8 : 
                            if y in x[1] : 
                                sudoku[x[0][0], x[0][1]] = y
                elif y in column_9_indices : 
                    for x in column_9_hash.items() : 
                        for y in unique_solutions_column_9 : 
                            if y in x[1] : 
                                sudoku[x[0][0], x[0][1]] = y
    return sudoku
# YOUR CODE HERE
#raise NotImplementedError()

All of your code must go above this cell. You may add additional cells into the notebook if you wish, but do not duplicate or copy/paste cells as this can interfere with the grading script.

### Testing Details
There are four difficulties of sudoku provided: very easy, easy, medium, and hard. There are 15 sample sudokus in each category, with solutions as well. Difficulty was determined using reference solvers, but your code may vary; it is conceivable that your code will find some sudokus much easier or harder within a given category, or even between categories.

*All categories that are easy and above will contain* ***invalid initial states***, that is, sudoku puzzles with no solution. In this case, your function should return a 9x9 NumPy array whose values are all equal to -1.

When we test your code, we will firstly test it on the *same* very easy puzzles that you have been given. Then we will test it on additional *hidden* sudokus from each difficulty in turn, easy and up – many more than 15 of each. Grades are awarded based on whether your code can solve the puzzles. For high grades on the hard puzzles, execution time will also be a factor. 

All puzzles must take under 20 seconds each on the test machine to count as successful – if it takes longer, it will timeout. Note that this is a maximum, not a goal. Higher grades require better performance on harder puzzles. As a very rough benchmark, you should be aiming for an average of under a second per puzzle. Hardware varies, but all tests will take place on the same modern desktop machine. Our ‘standard constraint satisfaction’ implementation takes about 0.001 seconds per puzzle for the very easy category, but struggles to solve some of the hard puzzles within the time limit.

***The hard sudokus are labelled as hard for a reason.*** We expect most submissions will not be able to solve them in a reasonable length of time. Use the stop button (■) on the toolbar if you need to terminate your code because it is taking too long.

The best way to improve the performance of your code is through a detailed understanding and smart choice of AI algorithms and data structures. This assignment is ***not*** meant to test your ability to write multi-threaded code or any other kind of high-performance code optimisations. 

#### Test Cell
The following code will run your solution over the provided sudoku puzzles. To enable it, set the constant `SKIP_TESTS` to `False`. If you fail any tests of one difficulty, the code will stop, but you can modify this behaviour if you like.

**IMPORTANT**: you must set `SKIP_TESTS` back to `True` before submitting this file!

In [6]:
SKIP_TESTS = True

def tests():
    import time
    difficulties = ['very_easy', 'easy', 'medium', 'hard']

    for difficulty in difficulties:
        print(f"Testing {difficulty} sudokus")
        
        sudokus = np.load(f"data/{difficulty}_puzzle.npy")
        solutions = np.load(f"data/{difficulty}_solution.npy")
        
        count = 0
        for i in range(len(sudokus)):
            sudoku = sudokus[i].copy()
            print(f"This is {difficulty} sudoku number", i)
            print(sudoku)
            
            start_time = time.process_time()
            your_solution = sudoku_solver(sudoku)
            end_time = time.process_time()
            
            print(f"This is your solution for {difficulty} sudoku number", i)
            print(your_solution)
            
            print("Is your solution correct?")
            if np.array_equal(your_solution, solutions[i]):
                print("Yes! Correct solution.")
                count += 1
            else:
                print("No, the correct solution is:")
                print(solutions[i])
            
            print("This sudoku took", end_time-start_time, "seconds to solve.\n")

        print(f"{count}/{len(sudokus)} {difficulty} sudokus correct")
        if count < len(sudokus):
            break
            
if not SKIP_TESTS:
    tests()

## Submission Test
The following cell tests if your notebook is ready for submission. **You must not skip this step!**

Restart the kernel and run the entire notebook (Kernel → Restart & Run All). Now look at the output of the cell below. 

*If there is no output, then your submission is not ready.* Either your code is still running (did you forget to skip tests?) or it caused an error.

As previously mentioned, failing to follow these instructions can result in a grade of zero.

In [8]:
def submission_tests():
    import sys
    import pathlib

    fail = False;

    if not SKIP_TESTS:
        fail = True;
        print("You must set the SKIP_TESTS constant to True in the cell above.")

    p1 = pathlib.Path('./readme.txt')
    p2 = pathlib.Path('./readme.md')
    if not (p1.is_file() or p2.is_file()):
        fail = True;
        print("You must include a separate file called readme.txt or readme.md in your submission.")

    p3 = pathlib.Path('./sudoku.ipynb')
    if not p3.is_file():
        fail = True
        print("This notebook file must be named sudoku.ipynb")

    if "sudoku_solver" not in globals():
        fail = True;
        print("You must include a function called sudoku_solver which accepts a numpy array.")
    else: 
        sudoku = np.load("data/very_easy_puzzle.npy")[0]
        solution = np.load("data/very_easy_solution.npy")[0]

        if not np.array_equal(sudoku_solver(sudoku), solution):
            print("Warning:")
            print("Your sudoku_solver function does not correctly solve the first sudoku.")
            print()
            print("Your assignment is unlikely to get any marks from the autograder. While we will")
            print("try to check it manually to assign some partial credit, we encourage you to ask")
            print("for help on the forum or directly to a tutor.")
            print()
            print("Please use the readme file to explain your code anyway.")

    if fail:
        print()
        sys.stderr.write("Your submission is not ready! Please read and follow the instructions above.")
    else:
        print("All checks passed. When you are ready to submit, upload the notebook and readme file to the")
        print("assignment page, without changing any filenames.")
        print()
        print("If you need to submit multiple files, you can archive them in a .zip file. (No other format.)")
        
submission_tests()

All checks passed. When you are ready to submit, upload the notebook and readme file to the
assignment page, without changing any filenames.

If you need to submit multiple files, you can archive them in a .zip file. (No other format.)


In [ ]:
# This is a TEST CELL. Do not delete or change.